from django.db import models


class Estados(models.TextChoices):
    ACRE: str = "AC", "Acre"
    ALAGOAS: str = "AL", "Alagoas"
    AMAPA: str = "AP", "Amapá"
    AMAZONAS: str = "AM", "Amazonas"
    BAHIA: str = "BA", "Bahia"
    CEARA: str = "CE", "Ceará"
    DISTRITO_FEDERAL: str = "DF", "Distrito Federal"
    ESPIRITO_SANTO: str = "ES", "Espírito Santo"
    GOIAS: str = "GO", "Goiás"
    MARANHAO: str = "MA", "Maranhão"
    MATO_GROSSO: str = "MT", "Mato Grosso"
    MATO_GROSSO_DO_SUL: str = "MS", "Mato Grosso do Sul"
    MINAS_GERAIS: str = "MG", "Minas Gerais"
    PARA: str = "PA", "Pará"
    PARAIBA: str = "PB", "Paraíba"
    PARANA: str = "PR", "Paraná"
    PERNAMBUCO: str = "PE", "Pernambuco"
    PIAUI: str = "PI", "Piauí"
    RIO_DE_JANEIRO: str = "RJ", "Rio de Janeiro"
    RIO_GRANDE_DO_NORTE: str = "RN", "Rio Grande do Norte"
    RIO_GRANDE_DO_SUL: str = "RS", "Rio Grande do Sul"
    RONDONIA: str = "RO", "Rondônia"
    RORAIMA: str = "RR", "Roraima"
    SANTA_CATARINA: str = "SC", "Santa Catarina"
    SAO_PAULO: str = "SP", "São Paulo"
    SERGIPE: str = "SE", "Sergipe"
    TOCANTINS: str = "TO", "Tocantins"
